// <auto-generated />
namespace PhoneCare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;

    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SecurityAndOrderFixes : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202605270001000_SecurityAndOrderFixes"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return null; }
        }
    }
}
