// <auto-generated />
namespace PhoneCare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SuaModelDonHang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SuaModelDonHang));
        
        string IMigrationMetadata.Id
        {
            get { return "202605212220407_SuaModelDonHang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
