// <auto-generated />
namespace PhoneCare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Update_KhoaTaiKhoan_To_Bit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_KhoaTaiKhoan_To_Bit));
        
        string IMigrationMetadata.Id
        {
            get { return "202604191557037_Update_KhoaTaiKhoan_To_Bit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
